name: "Auto Replace X in Issue Title"

on:
  issues:
    types: [opened]

jobs:
  update_issue_title:
    runs-on: ubuntu-latest
    steps:
      - name: Replace 'X' with issue number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          OLD_TITLE="${{ github.event.issue.title }}"

          # Replace 'X' with the actual issue number in the title
          NEW_TITLE=$(echo "$OLD_TITLE" | sed "s/X/$ISSUE_NUMBER/g")

          # Update issue title using GitHub API
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER} \
               -d "{\"title\": \"${NEW_TITLE}\"}"
